### ISSUE TITLE
What versions of MC is this being made for?

### ISSUE THREAD

**Issue by MechanosG** [Queerbric/Inspecio#1]
This looks neat.  Better than what's available on 1.16.4 (that I'm aware of).

I hate to be that guy.. let alone the first guy to ask.  But is there any plans for a 1.16.4 version, or any other versions?

**Comment by Boundarybreaker** [comment]
Sadly, Inspecio uses a new system first introduced in Minecraft 1.17 snapshots. Reimplementing it on 1.16.4 would require a lot of time and effort that just isn't worth it, I'm afraid.

**Comment by MechanosG** [comment]
Darn.  Alright, thanks.
