### ISSUE TITLE
Messed up colours of the shulker box previews

### ISSUE THREAD

**Issue by whitebear60** [Queerbric/Inspecio#102]
On 1.19.4 the shulker box preview colours are dimmed for some reason, with items being coloured along with the background, which wasn't happening on 1.19.3 (see screenshot below)

Minecraft 1.19.4
Quilt 0.18.6
Inspecio 1.8.0

![image](https://user-images.githubusercontent.com/42472132/230789916-14ebd62b-fe12-48ce-9763-39d3328af7fe.png)

**Comment by slushieuwu** [comment]
also seems to color toasts?
![image](https://user-images.githubusercontent.com/86991346/230823444-6ed25c96-de38-4338-b2ab-71236a30723a.png)

**Comment by slushieuwu** [comment]
yep, it colors all toasts
![image](https://user-images.githubusercontent.com/86991346/230823533-e37f8ce9-04b6-4332-a27e-c06fca90950a.png)

**Comment by zer0p1us** [comment]
As a temporary fix you can turn off the colour of shulker boxes in the config file
