### ISSUE TITLE
1.19.2 not open minecraft

### ISSUE THREAD

**Issue by Zumbisinho** [Queerbric/Inspecio#107]
I try to install the mod, but i can open because the mod 1.19.1-.1.19.2 only work on 1.19.1
![image](https://github.com/Queerbric/Inspecio/assets/124307188/005c3c18-ab97-4854-a55f-fbf4bef7ea10)

**Comment by LambdAurora** [comment]
Please install [Quilted Fabric API](https://modrinth.com/mod/qsl).
If Fabric API is present in your mods folder, remove it as well.
