### ISSUE TITLE
Crash when rendering entity on tooltip

### ISSUE THREAD

**Issue by Estrelaura** [Queerbric/Inspecio#13]
More specifically, the Horned Sheep from EarthtoJava. Reporting here first since the sheep renders just fine in the overworld.
[crash-2021-07-18_06.44.46-client.txt](https://github.com/Queerbric/Inspecio/files/6836014/crash-2021-07-18_06.44.46-client.txt)

**Comment by LambdAurora** [comment]
This issue must be reported to Earth2Java. Not an issue with Inspecio.

They unnecessarily cast the entity's world to `ServerWorld` while Inspecio gives a `ClientWorld`. A check should have been added by them. Worse is they cast to `ServerWorld` for a function (`readAngerFromNbt`) that doesn't even ask a `ServerWorld` and will do the check itself anyway.

**Comment by Slexom** [comment]
The issue has been fixed.
That cast was there from a year (2020/07/19) when I converted the mod from forge... why it was there? I dont'know, maybe because it was almost 2 am when commited the changes... XD
