### ISSUE TITLE
Soft crash on resource reload / end of game initialization when KubeJS is installed [1.17]

### ISSUE THREAD

**Issue by SebaSphere** [Queerbric/Inspecio#16]
When the latest [Inspecio build here](https://www.curseforge.com/minecraft/mc-mods/inspecio/files/3343900) is installed with the [latest KubeJS build + dependencies here](https://www.curseforge.com/minecraft/mc-mods/kubejs-fabric/files/3355296), the game will not start.

You can my latest.log file here: https://pastebin.com/3QneEaqk

Every resource reload, the game soft crashes and attempts to load again.

**Comment by SebaSphere** [comment]
I've posted the same issue on the KubeJS github here: https://github.com/KubeJS-Mods/KubeJS/issues/164

**Comment by LemmaEOF** [comment]
This deeeeefinitely looks like KubeJS' fault
