### ISSUE TITLE
Missing null-check on spawn egg item tooltip component. (entityType is null)

### ISSUE THREAD

**Issue by sm9cc** [Queerbric/Inspecio#18]
Hi there, when searching for items in REI, it crashes, I am not sure if this is a mod conflict.

Here is the crash report:

[gist.githubusercontent.com/natanfudge/ca3abd1d0ecea1ab4a723f38377f9612/raw/b98a5f934ffd70f64e3dfa519942a4e9e156d955/crash.txt](https://gist.githubusercontent.com/natanfudge/ca3abd1d0ecea1ab4a723f38377f9612/raw/b98a5f934ffd70f64e3dfa519942a4e9e156d955/crash.txt)

Thank you

**Comment by LemmaEOF** [comment]
~~Duplicate of #8 - REI's fault for making bad assumptions, impossible for us to fix. Ask shedaniel.~~ oh god this is a new one

**Comment by LambdAurora** [comment]
@Boundarybreaker I was going to say the same until I saw the crash report actually points out to something else, apparently it gets fed a totally empty spawn egg item somehow?

**Comment by LemmaEOF** [comment]
...what.
