### ISSUE TITLE
[QUESTION] AppleSkin-like features?

### ISSUE THREAD

**Issue by srnyx** [Queerbric/Inspecio#22]
Does this mod also show how much hunger/saturation the food your holding will replenish as AppleSkin does?

**Comment by LambdAurora** [comment]
The mod shows how much hunger/saturation the food will replenish only on tooltips, it's not intended to change the HUD though.

**Comment by srnyx** [comment]
> The mod shows how much hunger/saturation the food will replenish only on tooltips, it's not intended to change the HUD though.

Ah, alright, thanks!
