### ISSUE TITLE
Some tooltips seem to be missing config options to disable them

### ISSUE THREAD

**Issue by Kroppeb** [Queerbric/Inspecio#26]
I noticed while checking out the readme (and checked with the [config code](https://github.com/Queerbric/Inspecio/blob/1.17/src/main/java/io/github/queerbric/inspecio/InspecioConfig.java)) that some of the options are missing:
* lodestone coordinates
* repair cost
* beacon tooltips (also missing visual in the readme)

**Comment by LambdAurora** [comment]
Beacon tooltips are configurable and [the visuals are in the README](https://github.com/Queerbric/Inspecio#effects-tooltips).

Repair cost and lodestone coordinates only show up when advanced tooltips are enabled (with F3 + Q), I can add a config for those, but originally I didn't thought that a config would be needed for those 2 minor tooltips.

**Comment by Kroppeb** [comment]
> Beacon tooltips are configurable and the visuals are in the README.

Ah, I assumed the Modrinth would be the same as the README, apparently it's outdated.

> Repair cost and lodestone coordinates only show up when advanced tooltips are enabled (with F3 + Q), I can add a config for those, but originally I didn't thought that a config would be needed for those 2 minor tooltips.

I would prefer an (additional) config option for this. While for repair cost, it doesn't really matter as it's quite easy to check in vanilla too, showing the coordinates of a lodestone feels a bit cheaty. I know a lot of people who have advanced tooltips on to see what the exact durability of their tools/armor are, yet most would prefer to play without the lodestone compas coordinates.

**Comment by LambdAurora** [comment]
Ok!

Modrinth README is only synced with the features present in the latest version available on Modrinth.

**Comment by LambdAurora** [comment]
Fixed in Inspecio v1.2.0+1.18.
