### ISSUE TITLE
Crash with Earth2Java

### ISSUE THREAD

**Issue by AlisterGontineac** [Queerbric/Inspecio#30]
at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2945.method_12784(class_2945.java:81)
	at slexom.earthtojava.mobs.entity.passive.MuddyPigEntity.method_5693(MuddyPigEntity.java:110)
	at net.minecraft.class_1297.<init>(class_1297.java:275)
	at net.minecraft.class_1309.<init>(class_1309.java:237)
	at net.minecraft.class_1308.<init>(class_1308.java:122)
	at net.minecraft.class_1314.<init>(class_1314.java:12)
	at net.minecraft.class_1296.<init>(class_1296.java:28)
	at net.minecraft.class_1429.<init>(class_1429.java:40)
	at net.minecraft.class_1452.<init>(class_1452.java:59)
	at slexom.earthtojava.mobs.entity.base.E2JBasePigEntity.<init>(E2JBasePigEntity.java:18)
	at slexom.earthtojava.mobs.entity.passive.MuddyPigEntity.<init>(MuddyPigEntity.java:35)
	at net.minecraft.class_1299.method_5883(class_1299.java:475)
	at io.github.queerbric.inspecio.tooltip.SpawnEntityTooltipComponent.of(SpawnEntityTooltipComponent.java:51)
	at net.minecraft.class_1826.method_32346(class_1826.java:1044)
	at net.minecraft.class_1799.method_32347(class_1799.java:108)
	at net.minecraft.class_437.method_25409(class_437.java:168)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$ece000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.class_757.method_3192(class_757.java:876)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (243, 148). Absolute: (974.000000, 592.000000)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['AlisterGontineac'/386, l='ClientLevel', x=217.82, y=72.00, z=-286.58]]
	Chunk stats: 4096, 784
	Level dimension: minecraft:overworld
	Level spawn location: World: (177,71,-251), Section: (at 1,7,5 in 11,4,-16; chunk contains blocks 176,0,-256 to 191,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 45342 game time, 39043 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, visualoverhaul/fancyfurnace, visualoverhaul/nobrewingbottles, charmonium/journeyman, §bAVPBR-1-6+fixes.zip, Animated+Items.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 6659071784 bytes (6350 MiB) / 10737418240 bytes (10240 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.40
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37543.70
	Virtual memory used (MB): 28468.22
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 79.46
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms10240m -Xmx10240m
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.10
		actuallyunbreaking: Actually Unbreaking 1.17-0.2.0
		adorn: Adorn 2.1.3+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		amecs: Amecs 1.3.4+mc.1.17
		amecsapi: Amecs API 1.1.5+mc21w16a
		aqupdcaracal: Caracal mob 1.17-1.3.11
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		architectury: Architectury 2.4.25
		armor_hud: BerdinskiyBear's ArmorHUD 0.3.4
		audiooutput: AudioOutput 0.0.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		balm-fabric: Balm 1.3.0+0
		bannerpp: Banner++ 2.0.3+mc.1.17-rc1
		barrenisles: Barren Isles fabric-1.17-1.0.6
		bclib: BCLib 0.2.4
		betterend: Better End 0.10.5-pre
		betternether: Better Nether 5.1.3
		bettersodiumvideosettingsbutton: Better Sodium Video Settings Button 2.0.1
		bitsandchisels: BitsAndChisels 2.5.3
		blame: Blame 1.17-4.1.0-fabric
		blockshifter: Blockshifter 1.4.0+fabric-1.17.1
		blur: Blur (Fabric) 2.1.0
		caelus: Caelus API 0.0.16-1.17
		cakechomps: Cake Chomps 1.4.0-1.17
		campfiresmelting: Campfire Smelting 2.0.0
		cardinal-components: Cardinal Components API 3.0.0
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-block: Cardinal Components API (blocks) 3.0.0
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cardinal-components-item: Cardinal Components API (items) 3.0.0
		cardinal-components-level: Cardinal Components API (world saves) 3.0.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.0.0
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		carpet: Carpet Mod 1.4.44
		carpet-extra: Carpet Extra 1.4.43
		carrier: Carrier 1.8.0
		caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld: Caves and Cliffs add-on for William Wythers Overhauled Overworld 1.3
		centeredinventory: Centered inventory 1.0.3
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chat-up: Chat Up! 2.0
		chat_heads: Chat Heads 0.3+1.17
		clayrecipefabric: Clay Recipe 2.0.0
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		coat: Coat 1.0.0-beta.10
		com_alibaba_fastjson: fastjson 1.2.56
		com_cedarsoftware_json-io: json-io 4.10.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_focamacho_sealconfig: sealconfig 1.2.2
		com_googlecode_json-simple_json-simple: json-simple 1.1.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		command-gui-buttons: Command GUI Buttons 1.2.0
		completeconfig: CompleteConfig 1.1.0
		controlling: Controlling For Fabric 1.1.2
		copperequipment: Copper Equipment 1.5
		creativeonepunch: Creative One-Punch 1.2
		croptopia: Croptopia 1.6.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		decorative: Decorative 4.1.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		earthtojavamobs: Earth2Java 1.7.2+1.17
		editsign: EditSign 2.2.2
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enchantedbookredesign: Enchanted Book Redesign 1.17.1-2.0
		enchantment_lore: EnchantmentLore 1.2+MC1.17.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
		enhanced_mushrooms: Enhanced Mushrooms 1.0.5
		enhancedblockentities: Enhanced Block Entities 0.4.1+1.17
		entitybanners: Entity Banners 1.0.2-BETA+1.17
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.1
		expandedstorage: Expanded Storage 7.0.0-alpha.37
		extrasounds: Extra Sounds 1.4.1
		fabric: Fabric API 0.37.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+9e521e13d5
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b4463d5
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fake-player-api: Fake Player API 0.2.0
		fallingattack: Falling Attack 1.17.1-1.1.0
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fallingtree: FallingTree 2.13.0
		fastchest: FastChest 1.2+1.17
		fastfurnace: FastFurnace 1.17-3.0
		fasttransferlib: Fast Transfer Lib 0.5.5
		fenceplayerupper: Fence Player Upper 1.1.3+1.17.pre1
		ferritecore: FerriteCore 3.0.1
		fiber: fiber 0.23.0-2
		frex: FREX 5.2.223
		geckolib3: Geckolib 3.0.11
		glowingbanners: Glow Banners 1.0.2
		gravityguns: Gravity Guns 0.1.3
		guardiansgalore: GuardiansGalore 1.17.1-2.1
		hctm-base: HCTM Base 3.6.2
		hookshot: Hookshot 18.0
		hydrogen: Hydrogen 0.3
		identity: Identity 1.14.2-beta-1.17
		illuminations: Illuminations 1.6.3
		indium: Indium 1.0.0+mc1.17.1
		indrev: Industrial Revolution 1.10.0-alpha.12
		inspecio: Inspecio 1.1.0+1.17
		iris: Iris 1.1.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		json-model-extensions: JSON Model Extensions 1.22.200
		kibe: Kibe 1.8.1-BETA+1.17
		kirin: Kirin UI 1.9.1
		krypton: Krypton 0.1.4
		ktrl: Kontrolo 1.5.0+1.17
		led: Light Emitting Diode 1.1.0
		lengthyladders: Lengthy Ladders 1.0.4
		libaddict: libaddict 0.3.0
		libblockattributes: LibBlockAttributes 0.8.17003
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.5+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lifts: Lifts 1.2-BETA+1.17
		lithium: Lithium 0.7.3
		loading-timer: Loading Timer 1.5.0-Beta1
		lovely_snails: Lovely Snails 1.0.2+1.17
		magna: Magna 1.5.5-1.17-pre4
		malilib: MaLiLib 0.10.0-dev.24
		mavm: More Axolotl Variants Mod 1.0.2b
		maybe-data: Maybe data 1.0.1-1.17
		megane: megane 5.1.2
		megane-base: megane-base 5.1.2
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.1.2+0.4.2
		megane-industrial-revolution: megane-industrial-revolution 5.1.2+1.10.0-alpha.4
		megane-kibe: megane-kibe 5.1.2+1.7.2-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.1.2+0.9.0
		megane-runtime: megane-runtime 5.1.2
		megane-team-reborn-energy: megane-team-reborn-energy 5.1.2+0.1.1
		megane-vanilla: megane-vanilla 5.1.2+1.17.1
		midnightlib: MidnightLib 0.2.3
		minecraft: Minecraft 1.17.1
		miniextras: Mini Extras Mod 1.3.1+1.17
		modid: Food+ 1.0
		modmanager: Mod Manager 1.0.1+1.17-alpha
		modmenu: Mod Menu 2.0.5
		mooblooms: Mooblooms 1.5.1
		morebannerfeatures: More Banner Features 1.0.2
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousewheelie: Mouse Wheelie 1.7.3-newconfig.2+mc1.17.1-pre1
		music_control: Music Control 1.5+1.17.1
		mythic-mounts: Mythic Mounts 1.17.1-1.1
		nmuk: No More Useless Keys 1.0.1+mc1.17
		nofade: No Fade 1.17-2.0.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		npcvariety: NPC Variety 2.1.2
		omega-config: OmegaConfig 1.0.8
		onebar: OneBar 1.6.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_objenesis_objenesis: objenesis 3.2
		patchouli: Patchouli 1.17.1-55-FABRIC-SNAPSHOT
		persistentgamemodeswitcher: PersistentGamemodeSwitcher 1.0.2.2
		petowner: Pet Owner 1.8.1-1.17-rc1+
		physicsmod: Physics Mod 2.5.5
		pigpoop: Pig Poop 1.0.0
		plantinajar: Plant In A Jar 2.2.2
		player_transport_ducts: Player Transport Ducts 1.0.2
		playerabilitylib: Pal 1.3.0
		pling: Pling 1.4.0
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		prone: prone 0.1.4
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		rayon: Rayon 1.3.1
		rayon-core: Rayon Core API 1.3.1
		rayon-entity: Rayon Entity API 1.3.1
		rayon-particle: Rayon Particle API 1.3.1
		redbits: Red Bits 1.10.0
		reeses-sodium-options: Reese's Sodium Options 1.1.2
		repurposed_structures: Repurposed Structures 2.3.1+1.17.1
		roughlyenoughitems: Roughly Enough Items 6.0.267-alpha
		rswires: RSWires 4.11.2
		satin: Satin 1.6.0-nightly.1.17-pre3
		schmucks: Schmucks 1.4.0
		seamless_loading_screen: Seamless Loading Screen 1.3.6+1.17.1
		searchablecontainers: Searchable Containers 1.3
		slotlink: slotlink 3.0.10
		sodium: Sodium 0.3.0+IRIS2
		sodium-extra: Sodium Extra 0.3.3
		spyzoom: Spyglass Zoom 1.0.1
		stacc: Stacc 1.2.3
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		talking-villagers: Talking Villagers 1.1.3
		team_reborn_energy: Energy 0.1.1
		the_bumblezone: The Bumblezone - Fabric 3.0.9+1.17.1
		tillitbreaks: Till it Breaks 0.3.2
		trampledisablerfabric: Trample Disabler 1.0.3
		transporter: Transporter 1.1.1-1-ga89c16c
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.2
		tweakeroo: Tweakeroo 0.10.0-dev.20210710.155746
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.1.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.1
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		vanillaexcavators: Vanilla Excavators 1.1.0
		verticalrepeaters: Vertical Repeaters 1.1.2
		villagernames: Villager Names 2.0.0
		visualoverhaul: VisualOverhaul 3.3.0
		waterdripsound: Drip Sounds 1.17-0.2.2
		waystones: Waystones 8.1.1+0
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.6
		worldmesher: Worldmesher 0.1
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.16.0
		xaeroworldmap: Xaero's World Map 1.16.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.68, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, visualoverhaul/fancyfurnace, visualoverhaul/nobrewingbottles, charmonium/journeyman, file/§bAVPBR-1-6+fixes.zip, file/Animated+Items.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 
	Player Count: 1 / 8; [class_3222['AlisterGontineac'/386, l='ServerLevel[Saturn]', x=217.82, y=72.00, z=-286.58]]
	Data Packs: vanilla, Fabric Mods, file/Repurposed_Structures-Charm-v2.zip, file/Everything+1.0.1.zip
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Earth2Java (earthtojavamobs), Fabric Loader (fabricloader), Inspecio (inspecio)

**Comment by LambdAurora** [comment]
We cannot fix the issue, Earth2Java does a premature cast of the world without checking if it can.
