### ISSUE TITLE
Crash when looking up anything in REI 6.1.329

### ISSUE THREAD

**Issue by SplendidAlakey** [Queerbric/Inspecio#40]
**MC** 1.17.1
**Fabric** loader 0.12.5; API 0.42.1
**Inspecio** inspecio-1.1.0+1.17
**REI** RoughlyEnoughItems-6.1.329

1. Install all of the above mods, launch the game and create a world (or enter an existing one)
2. Open up REI and type anything in the search field (I type "a" as an example)
3. The game will crash immediately

Logs: https://gist.github.com/Footage2-Amply-Pounce/3893fc3b30bbb2be96eecc1bc48d6243

**Comment by LemmaEOF** [comment]
Initial investigations seem like it might actually be a fabric bug this time! We'll keep digging.

**Comment by SplendidAlakey** [comment]
Closing this issue for multiple reasons. It doesn't happen on 1.18.2, I'm never going back to anything below 1.18 and the latest Inspecio release is marked as the last one for fabric.
