### ISSUE TITLE
Running Inspecio in 1.18, the visuals are blank.

### ISSUE THREAD

**Issue by SpadeTheSkeleton** [Queerbric/Inspecio#43]
When hovering over a food item or anything this mod has to offer, it's just all blank. 

The list of mods running and images of the issue.
![image](https://user-images.githubusercontent.com/87557897/144472981-ded2b1ed-0006-4aeb-94a0-d0c017ef14f3.png)
![image](https://user-images.githubusercontent.com/87557897/144472408-ace77598-35d3-4fa9-bc13-0ecc182e8a26.png)

![image](https://user-images.githubusercontent.com/87557897/144470797-f8c34225-9560-473f-8645-40d7a3845cff.png)
![image](https://user-images.githubusercontent.com/87557897/144470911-3451baa3-a74e-4927-a902-5e7490e42641.png)
![image](https://user-images.githubusercontent.com/87557897/144471112-736c9079-2b30-40f5-89b2-5e469ee36601.png)

**Comment by private-effort** [comment]
I have same issue

**Comment by hamcoremusic** [comment]
+1

**Comment by Eclipse-Sol** [comment]
Same issue here, only using Inspecio and FAPI

**Comment by KasraIDK** [comment]
+1

**Comment by vivyir** [comment]
+1

**Comment by Spixa** [comment]
+2

**Comment by LambdAurora** [comment]
I think there's enough comments reporting the same issue.

**Comment by Kynz0** [comment]
same pls fix

**Comment by danield4n13l** [comment]
+1, couldn't find a fix

**Comment by CrafterCZ** [comment]
+1
Also ye, would be awesome to get a response to atleast one of the comments :D

**Comment by JadeJuno** [comment]
if you build it with the 1.18 branch's code it works, but hovering over a beacon crashes the game (#50)
Edit: the crash has been fixed apparently

**Comment by duartenina** [comment]
> if you build it with the 1.18 branch's code it works, but hovering over a beacon crashes the game (#50)

Is there a prebuilt release of the 1.18 branch?

**Comment by pydubz08** [comment]
> > if you build it with the 1.18 branch's code it works, but hovering over a beacon crashes the game (#50)
> 
> Is there a prebuilt release of the 1.18 branch?

I also wanted to know

**Comment by JadeJuno** [comment]
> > if you build it with the 1.18 branch's code it works, but hovering over a beacon crashes the game (#50)
> 
> Is there a prebuilt release of the 1.18 branch?

Not that I know of. Only way to play the 1.18 branch is to build it yourself.

**Comment by AnalogCyan** [comment]
@duartenina @Golder06 
https://github.com/Queerbric/Inspecio/actions/runs/1628477168

This is the latest 1.18 build from the workflows on this repo. It includes d3d27f3 which fixes issue #50.

**Comment by JadeJuno** [comment]
> @duartenina @Golder06 https://github.com/Queerbric/Inspecio/actions/runs/1628477168
> 
> This is the latest 1.18 build from the workflows on this repo. It includes [d3d27f3](https://github.com/Queerbric/Inspecio/commit/d3d27f3232cae27089058545f59faab7723d96ef) which fixes issue #50.

Aight, glad I was wrong then, thanks!

**Comment by LambdAurora** [comment]
Fixed with Inspecio 1.2.0+1.18.
