### ISSUE TITLE
1.16 version

### ISSUE THREAD

**Issue by ThatTonybo** [Queerbric/Inspecio#44]
Is there a 1.16.5 version?

**Comment by SpadeTheSkeleton** [comment]
No. Only 1.17 and 1.18 (but 1.18 is bugged at the moment.) & this isn't the spot to ask if there's another version of this mod. You can look both on Modrinth and curse forge to look if there was a 1.16.5 version.

**Comment by LambdAurora** [comment]
This was already answered in #2, and that one is pinned.
