### ISSUE TITLE
Inspecio is outdated, breaks KubeJS

### ISSUE THREAD

**Issue by MJRamon** [Queerbric/Inspecio#47]
Looks like Inspecio (besides broken features) is breaking KubeJS in 1.18.1
https://github.com/KubeJS-Mods/KubeJS/issues/237

**Comment by LemmaEOF** [comment]
KubeJS makes a bad assumption on the existence of its script manager. I've included details in that KubeJS issue. We cannot fix this without breaking a critical part of the mod, so KubeJS should make a null-check to prevent itself from crashing when it's in a different environment.
