### ISSUE TITLE
[1.18.1] Add support for Simple Back Mod

### ISSUE THREAD

**Issue by kwpugh** [Queerbric/Inspecio#53]
Hi,

I make a backpack mod https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric and I have had several requests to add a "hover over to see contents" feature to my mod.  Would you be willing to add support for my mod into yours?  

Thank you for considering.

Regards,

Kevin

**Comment by LambdAurora** [comment]
As-of latest release, this mod contains an API to allow this:

You first need to use Modrinth's maven stuff to import the mod into your project, then create a new class that implements `InspecioEntrypoint` and add it to your fabric.mod.json (`inspecio` entrypoint).
In the method there, you can register a [`InventoryProvider`](https://github.com/Queerbric/Inspecio/blob/1.18/src/main/java/io/github/queerbric/inspecio/api/InventoryProvider.java) for your item.

Sadly, currently there's no other methods that allow to avoid such hard dependencies, [QSL's registry dictionary API](https://github.com/QuiltMC/quilt-standard-libraries/pull/29) might help in the future, but it's currently not available.

**Comment by kwpugh** [comment]
ok, will handle this on my side.
