### ISSUE TITLE
3 way mod conflict between REI, guard villagers (fabric) and inspecio [Bug]

### ISSUE THREAD

**Issue by BossCreeper81** [Queerbric/Inspecio#61]
Game crashes when searching anything, while REI, guard villagers and Inspecio are installed.

1 .Install REI, Inspecio and Guard villagers (fabric)
2. Start the game
3. Crash
 
Disabling the search tooltip feature in REI "fixes" the bug

1.18.1
fabric

logs:
https://pastebin.com/xcPZP2si //only the 3 mods and their dependencies installed
https://crashy.net/43KxFDcVH6NL5g7QqqM2 // crashy with my full setup

Removing either inspecio or guard villagers also fixes the bug

[shedaniel/RoughlyEnoughItems#740]

**Comment by LambdAurora** [comment]
This is very clearly an issue in Guard Villagers itself, this issue is identical to #33, #30, and #13.

**Comment by BossCreeper81** [comment]
Thanks for the fast reply!
