### ISSUE TITLE
Effects added to Vanilla food don't show up on tooltips

### ISSUE THREAD

**Issue by Estrelaura** [Queerbric/Inspecio#64]
Some mods like Actually Glow Berries add effects to existing Vanilla food. Others, like Pale change the effect a food is supposed to give. In both cases, the tooltip will render with no effects, showing only the recovered hunger.

**Comment by LambdAurora** [comment]
If those effects are added through a custom event there is no way for the mod to know about those in advance and display them in the tooltips.
