### ISSUE TITLE
Bundled quiltified fabric api breaks with CITResewn

### ISSUE THREAD

**Issue by Justsnoopy30** [Queerbric/Inspecio#66]
Error log: https://paste.gg/p/anonymous/0fa7aa88d2cf42f089655db86c7e02da

**Comment by LambdAurora** [comment]
This probably should be reported to CITResewn, it relies on an implementation class of FAPI, which is really not good.

After looking at it, its usage is really not justified as the implementation of it already does what CITResewn tries to do.

**Comment by LambdAurora** [comment]
Versions of Inspecio that bundled Quiltified Fabric API are no unsupported, Inspecio is only supported on Quilt loader now.
