### ISSUE TITLE
Breaks Continuity (1.18.2)

### ISSUE THREAD

**Issue by craftycorvid** [Queerbric/Inspecio#70]
Trying to use both continuity and inspecio breaks the functionality of continuity. Game still runs, but textures not connected. Both of these mods worked fine together before 1.18.2

Mod List:
```
continuity-1.1.0+1.18.2.jar
fabric-api-0.48.0+1.18.2.jar
inspecio-1.3.0+1.18.jar
```

Thanks for the great mod, let me know if there's anything else I can provide to help track this issue down.

**Comment by LambdAurora** [comment]
Fixed with 1.3.1.
