### ISSUE TITLE
Bee hive honey level

### ISSUE THREAD

**Issue by clarfonthey** [Queerbric/Inspecio#71]
Silk-touched hives not only store the number of bees, but the honey level as well. This can actually be observed by the stacking behaviour of empty bee hives -- empty hives with the same honey level will stack, but only if they have the same level.

Would be nice if this could be shown as well!

Also, thank you for the lovely mod <3

**Comment by LambdAurora** [comment]
![image](https://user-images.githubusercontent.com/12587332/182407118-74bd00d3-8b17-405f-ba4a-17fe27443d62.png)

Coming to an Inspecio near you soon.

**Comment by LambdAurora** [comment]
Added in Inspecio 1.6.0.
