### ISSUE TITLE
[Crash] - [Incompatible] - Crashes LevelZ Datapack when Vanilla Hammers & Inspecio & LevelZ are present

### ISSUE THREAD

**Issue by xR4YM0ND** [Queerbric/Inspecio#72]
Hey there,

so this bug is very uncommon 

when you use LevelZ Mod, Inspecio Mod & Vanilla Hammers Mod -> the Datapack for LevelZ doesnt work

"Maybe some Packets are restricted"

Fabric 1.18.2 - 0.13.3

In this latest.log, i hovered over a "bow" and the game crashes. 

This is cause of LevelZ, but this only comes cause the datapack for levelz isnt loaded cause of the combination of vanilla hammers & inspecio

When i use LevelZ with Vanilla Hammers , the Datapack for LevelZ is loaded and all works fine
When i use LevelZ with Inspecio, the Datapack for LevelZ is loaded and all works fine
When i use all 3 (LevelZ , Inspecio & Vanilla Hammers), the Datapack for LevelZ isnt loaded (Packets)

[Latest.Log](https://gist.github.com/SpigotDE/b9e51d8465099029a66a4102f7d3fb60)
[Crash Report](https://gist.github.com/SpigotDE/807412efc1c706c9d7e28132d87fee31)

**Comment by xR4YM0ND** [comment]
Vanilla Hammers Issue https://github.com/Draylar/vanilla-hammers/issues/115

**Comment by xR4YM0ND** [comment]
LevelZ Issue: https://github.com/Globox1997/LevelZ/issues/117

**Comment by Globox1997** [comment]
For some reason the SimpleSynchronousResourceReloadListener doesn't execute the reload method when those three mods are loaded.

**Comment by xR4YM0ND** [comment]
I think its inspecio mainly 

I have this bug with inspecio + other mods ( vanilla hammers / charm )

**Comment by LambdAurora** [comment]
Inspecio 1.3.x for Minecraft 1.18.2 is no longer supported. Inspecio for Minecraft 1.18.2+ only runs on Quilt Loader.
