### ISSUE TITLE
Inspecio breaks Continuity [1.18.2]

### ISSUE THREAD

**Issue by DustGalaxy** [Queerbric/Inspecio#77]
Textures is not connecting. 
Fabric API 0.48.0+ 1.18.2
Continuity 1.1.0+ 1.18.2
Inspecio 1.3.0+1.18
 
![image](https://user-images.githubusercontent.com/103292379/162548680-1a8c0030-8fb8-404a-b2f6-b6e0cbf0dbbf.png)

**Comment by LambdAurora** [comment]
Inspecio 1.3.0 is no longer supported, and now requires the Quilt Loader.
