### ISSUE TITLE
[Feature suggestion] Mob spawner tooltip

### ISSUE THREAD

**Issue by ShaneTRS** [Queerbric/Inspecio#91]
Mob Spawners have NBT tags similar to spawn eggs (with the exception of SpawnPotentials), so it should be relatively easy to implement. 
![image](https://user-images.githubusercontent.com/80662335/177596971-4d25fc2c-2f81-4789-8eae-0ef210bb9692.png)

**Comment by LambdAurora** [comment]
Added in Inspecio 1.6.0.
