### ISSUE TITLE
I would like you to transfer the mod from qulit to fabric

### ISSUE THREAD

**Issue by Silver00177** [Queerbric/Inspecio#99]
I would like you to transfer the mod from qulit to fabric

**Comment by LemmaEOF** [comment]
No can do - this mod only works because of Quilt's tooltip API. It cannot work on Fabric.

**Comment by LambdAurora** [comment]
I invite you to read [Quilt's newcomer guide](https://quiltmc.org/en/about/newcomer-guide/). Fabric mods work on Quilt. And as it was said, Inspecio makes use of Quilt-only APIs that do no exist on Fabric.

**Comment by ahmed12345678910111213141516** [comment]
so this mod wont have a newer fabric versions?

**Comment by LemmaEOF** [comment]
Nope, it's not possible. Try switching over to Quilt.
